import pandas as pd
import json

# Note: Update this path to match an actual file generated by extract_nyc311.py
sample_file_path = 'data/staging/nyc311_raw_20240101_120000.json'

try:
    df = pd.read_json(sample_file_path)

    print("=== DATA QUALITY REPORT ===\\n")

    # 1. Missing values
    print("Missing Values:")
    print(df.isnull().sum().sort_values(ascending=False).head(10))
    print("\\n")

    # 2. Date columns
    date_cols = ['created_date', 'closed_date', 'resolution_action_updated_date']
    print(f"Date columns: {date_cols}")
    print(df[date_cols].head())
    print("\\n")

    # 3. Complaint types
    print(f"Unique complaint types: {df['complaint_type'].nunique()}")
    print("\\nTop 10 complaint types:")
    print(df['complaint_type'].value_counts().head(10))
    print("\\n")

    # 4. Boroughs
    print("Borough distribution:")
    print(df['borough'].value_counts(dropna=False))

except FileNotFoundError:
    print(f"File {sample_file_path} not found. Please run extract_nyc311.py first and update the path.")
